Gg 8142 record support
BertschiAG/ARCHIVED_easy-random pull request #2
Opened 2022-12-16 15:03 UTC by widste

Thank you for taking time to contribute this pull request :smile:

You have probably already checked the following points, but as a reminder, please ensure that:

* your branch is rebased on the latest version of the master branch
* all tests pass
* code is formatted with IntelliJ Idea default settings (if you use another IDE, never mind, ignore this point)

You may add the reference of the issue in your commit message.

Don't hesitate to add your name to the contributors list in the `README.md` file.

Many thanks upfront!

2022-12-16 15:18 UTC, dosomder commented
It's a bit a weird fork structure now. easy-random -> Yspadadden -> BertschiAG. I didn't realize this during our call. I guess this make staying up to date with the parent a bit more complicated

2022-12-19 07:16 UTC, dosomder commented
Do you have it used in a Bertschi project? Example: You could readd the test in SP: https://bitbucket.org/bertschiagch/opsshipmentplanner/commits/647bb7cadb5f06f676b4d25af003ee1afc7a418c

2022-12-19 07:16 UTC, dosomder requested changes

2022-12-19 07:16 UTC, dosomder commented on easy-random-core/src/main/java/org/jeasy/random/EasyRandom.java
> +            // whose descriptor is the same as the record descriptor;"
You can probably remove the newline here

2022-12-19 07:16 UTC, dosomder commented on easy-random-core/src/main/java/org/jeasy/random/EasyRandom.java
> +        return new ArrayList<>(asList(type.getDeclaredFields()));
Is the additional wrapping to ArrayList necessary?

2022-12-19 07:16 UTC, dosomder commented on easy-random-core/src/main/java/org/jeasy/random/FieldPopulator.java
> +
The style in this method seems to be compact (no newline between ifs) so this newline seems out of place

2022-12-19 07:16 UTC, dosomder commented on easy-random-core/src/main/java/org/jeasy/random/FieldPopulator.java
> +                    // FIXME catch ObjectCreationException and throw ObjectCreationException ?
What does this mean?

2022-12-19 07:16 UTC, dosomder commented on easy-random-core/src/main/java/org/jeasy/random/FieldPopulator.java
> +    <T> T populateField(final Class<T> target, final Field field, final RandomizationContext context) {
Should we name this createInstance or something like that to distinguish from the other populateField that takes already a created instance?

2022-12-19 07:16 UTC, dosomder commented on easy-random-core/src/main/java/org/jeasy/random/FieldPopulator.java
>      void populateField(final Object target, final Field field, final RandomizationContext context) throws IllegalAccessException {
I think we could theoretically remove this altogether and switch to the other style for all objects (creating obj via constructor), right? But it seems to me that we want to prevent rewriting existing code, as long that it works. So this is fine.

2022-12-19 08:10 UTC, widste commented on easy-random-core/src/main/java/org/jeasy/random/api/TypeResolver.java
> +/*
With this maven plugin the header is set automatically to all java files:

```
<plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${maven-license-plugin.version}</version>
                <configuration>
                    <header>licence-header-template.txt</header>
                    <properties>
                        <currentYear>2020</currentYear>
                    </properties>
                    <strictCheck>true</strictCheck>
                    <includes>
                        <include>src/**/*.java</include>
                    </includes>
                    <mapping>
                        <java>SLASHSTAR_STYLE</java>
                    </mapping>
                </configuration>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
As this change was merged by Mario, but maven wasn't executed now this header was added

2022-12-19 08:13 UTC, widste commented on easy-random-core/src/test/java/org/jeasy/random/beans/SimpleRecord.java
> +  public SimpleRecord(SimpleRecord in) {
That's was we defined in OPS

2022-12-19 08:17 UTC, widste commented on easy-random-core/src/test/java/org/jeasy/random/EasyRandomTest.java
> +    @Disabled
Does also fail on easy-random master, didn't invest time to fix it and wanted to have a state where unit tests are running in case of further commits

2022-12-19 08:24 UTC, widste commented on easy-random-core/src/main/java/org/jeasy/random/EasyRandom.java
> +        return new ArrayList<>(asList(type.getDeclaredFields()));
Not required, just reused it as it is in ReflectionUtils.getDeclaredFields()
Will remove it

2022-12-19 08:31 UTC, dosomder commented on easy-random-core/src/test/java/org/jeasy/random/EasyRandomTest.java
> +    @Disabled
Wait, they have tests on master that are not even running? Interesting

2022-12-19 11:36 UTC, widste commented on easy-random-core/src/main/java/org/jeasy/random/FieldPopulator.java
> +                    // FIXME catch ObjectCreationException and throw ObjectCreationException ?
I reused the code from populateField
Think the comment is because of catching any throwing the same type of exception
If preferred could remove the try/catch block

2022-12-19 13:08 UTC, dosomder commented on easy-random-core/src/main/java/org/jeasy/random/FieldPopulator.java
> +                    // FIXME catch ObjectCreationException and throw ObjectCreationException ?
Not sure how the raw exception message looks like. It's probably useful to have the field name / type. So we can just leave this

2022-12-19 13:09 UTC, dosomder approved these changes

2022-12-20 09:54 UTC, merged